### ISSUE TITLE
BBCI data format

### ISSUE THREAD

**Issue by ZQInQAAS** [robintibor/fbcsp#2]
hello, I wonder where i can get the BBCI data in 'examples\FBCSP-Motor.ipynb' 
'data/BBCI-only-last-runs/BhNoMoSc1S001R13_ds10_1-2BBCI.mat' or this data format?

**Comment by robintibor** [comment]
HI! Unfortunately this data is not publicly available at the moment! We will announce if we have made it available! However the remaining code should work with publicly available data like that https://robintibor.github.io/braindecode/notebooks/TrialWise_Decoding.html or that https://github.com/robintibor/braindecode/blob/master/examples/bcic_iv_2a.py
