### ISSUE TITLE
 error:"the leading minor of order 7 of 'b' is not positive definite."

### ISSUE THREAD

**Issue by ZQInQAAS** [robintibor/fbcsp#3]
After I loaded BCIC data, I got an error in computing matrix decomposition(fbcsp\signalproc.py):
`d, v = sp.linalg.eigh(c2, c1 + c2)`
the error log is:

> numpy.linalg.linalg.LinAlgError: the leading minor of order 4 of 'b' is not positive definite. The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.

I found a similar problem in [https://stackoverflow.com/questions/31685486/what-could-be-causing-the-leading-minor-of-order-n-is-not-positive-definite](url), but I've not get an solution.
My python version is 2.7.

**Comment by ZQInQAAS** [comment]
I don't know if that solves the problem, I changed 
`d, v = sp.linalg.eigh(c2, c1 + c2)` to
`d, v = sp.linalg.eig(c2, c1 + c2)` and it works.

**Comment by robintibor** [comment]
Hi, We chose eigh on purpose but are also not sure about precide differences. In general, maybe have  a look at the covariance matrices if there are zeros or very large or very small values... But eig should be ok as well...
